services:
  - type: web
    name: zurich-showcase
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn showcase.wsgi:application"
    envVars:
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
