# Generated by Django 6.0.6 on 2026-06-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebsiteTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ecommerce", "E-Commerce"),
                            ("restaurant", "Restaurant"),
                            ("portfolio", "Portfolio"),
                            ("real_estate", "Real Estate"),
                            ("health", "Health & Clinic"),
                            ("school", "School / Education"),
                            ("hotel", "Hotel & Hospitality"),
                            ("ngo", "NGO / Nonprofit"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="thumbnails/")),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. previews/restaurant.html",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
    ]
